// routes/dataRoutes.js
const express = require("express");
const dataController = require("../controllers/dataController");
const router = express.Router();

const multer = require('multer');
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 1 * 1024 * 1024 }, 
  });

  router.get("/locationno",dataController.getLocationno)
  router.post("/locationSearchdata",dataController.getlocationsearchdata)
  router.post("/addlocationinfo",dataController.addlocationinfo)
  router.post("/location_no",dataController.locationsaveEditedData)
  router.post("/deletelocation",dataController.locationdeleteData)
  router.post("/LocationUpdate", dataController.LocationUpdate)
  router.post("/forgetPassword", dataController.forgetPassword);
  router.post("/Passwords",dataController.Passwords)
  router.post("/login", dataController.login);
  router.get ("/userData", dataController.getAlluserData)
  router.post("/useradd",upload.single('user_img'),dataController.userAddData)
  router.post("/userupdate", dataController.UsersaveEditedData)
  router.post("/userdelete", dataController.UserdeleteData)
  router.post("/usersearchcriteria",dataController.getUsersearchdata)
  router.post("/UpdateUserImage",upload.single('user_img'),dataController.UpdateUserImage)
  router.post("/UserUpdates", upload.single('user_images'), dataController.UserUpdate)
  router.post("/Userdropdown",dataController.Userdropdown)
  router.get("/CompanyMappingData",dataController.getAllCompanyMappingData)
  router.post("/addCompanyMappingData",dataController.addCompanyMappingData)
  router.post("/companymappingsearchdata",dataController.getcompanymappingsearchdata)
  router.post("/getusercompany",dataController.getusercompany)
  router.post("/updcompanymapping",dataController.updcompanymapping)
  router.post("/commappingdeleteData",dataController.commappingdeleteData)
  router.post("/CompanyMappingUpdate", dataController.CompanyMappingUpdate)
  router.get("/UserRoleMappingData",dataController.getAllUserRoleMappingData)
  router.post("/addUserRoleMappingData",dataController.addUserRoleMappingData)
  router.post("/userrolsearchdata",dataController.getUserrolesearchdata)
  router.post("/RollMappingDelete",dataController.RollMappingDelete)
  router.post("/updateRoleMapping",dataController.updateRoleMapping)
  router.post("/RoleMappingUpdate", dataController.RoleMappingUpdate)
  router.get("/userscreenmap", dataController.getAlluserscreenmap)
  router.post("/adduserscreenmap",dataController.adduserscreenmap)
  router.post("/saveEditeduserscreenmap",dataController.saveEditeduserscreenmap)
  router.post("/userscreenmapdeleteData",dataController.userscreenmapdeleteData)
  router.post("/userscreensearchdata",dataController.getuserscreensearchdata)
  router.post("/getUserPermission",dataController.getUserPermission)
  router.post("/roleid", dataController.getroleid)
  router.get("/RoleInfoData", dataController.getAllRoleInfoData)
  router.post("/addRoleInfoData", dataController.AddRoleInfoData)
  router.post("/Roleupdate", dataController.RolesaveEditedData)
  router.post("/Rolesearchdata",dataController.getRolesearchdata)
  router.post("/roledelete",dataController.roledeleteData)
  router.post("/UserRole",dataController.getUserRole)
  router.post("/RoleUpdates", dataController.RoleUpdate)
  router.post("/addattriData",dataController.addattrihdrData)
  router.post("/variant", dataController.getvariant)
  router.post("/uom", dataController.getuom)
  router.post("/city", dataController.getCity)
  router.post("/country", dataController.getCountry)
  router.post("/state", dataController.getState)
  router.post("/status", dataController.getStatus)
  router.post("/Shift", dataController.getShift)
  router.post("/Transaction", dataController.getTransaction)
  router.post("/gender", dataController.getGender)
  router.post("/Loginorout", dataController.getLoginorout)
  router.post("/delPer", dataController.getDeletepermission)
  router.post("/regbrand", dataController.getregisterbrand)
  router.post("/ourbrand", dataController.getourbrand)
  router.get("/hdrcode", dataController.gethdrcode)
  router.post("/Usertype", dataController.getUsertype)
  router.post("/screentype",dataController.getscreentype)
  router.post("/paytype", dataController.getPaytype)
  router.post("/purchasetype", dataController.getPurchasetype)
  router.post("/salestype", dataController.getSalestype)
  router.post("/ordertype", dataController.getordertype)
  router.post("/addattriData",dataController.addattrihdrData)
  router.get("/attributedetData",dataController.getAllattributedetData)
  router.post("/addattridetData",dataController.addattridetData)
  router.post("/delattridetData",dataController.deleteAttriDetailData)
  router.post("/updattridetData",dataController.updattridetData)
  router.post("/attributeSearchdata",dataController.getattributeSearchdata)
  router.post("/transactiontype",dataController.gettranstype)
  router.post("/Screens",dataController.getScreens)
  router.post("/Permissions",dataController.getPermissions)
  router.post("/getacctype",dataController.getacctype)
  router.post("/getofftype",dataController.getofftype)
  router.post("/getInventoryTransaction",dataController.getInventoryTransaction)
  router.post("/getEmptype", dataController.getEmptype)
  router.post("/Condition", dataController.getCondition)
  router.post("/AttributeUpdate", dataController.AttributeUpdate)
  router.post("/getEvent", dataController.getEvent)
  router.post("/getsiblings",dataController.getsiblings)
  router.post("/getKids",dataController.getkids)
  router.post("/getMartial",dataController.getMartial)
  router.post("/getSalaryType",dataController.getSalaryType)
  router.post("/getPayscale",dataController.getPayscale)
  router.post("/getLoanID",dataController.getLoanID)
  router.post("/getItem",dataController.getItem) 
  router.post("/getDocumentType",dataController.getDocumentType)
  router.post("/getrelation",dataController. getrelation)
  router.post("/getannoncementtype",dataController. getannoncementtype)
  router.post("/getAnnouncementDetail",dataController. getAnnouncementDetail)
  router.post("/getAnnouncement_Msg",dataController. getAnnouncement_Msg)
  router.get("/getAnnouncementDetail",dataController.getAnnouncement)
  router.post("/getcompanyshift",dataController.getcompanyshift)
  router.post("/getOverallTAX",dataController.getOverallTAX)
  router.post("/getInvocieType",dataController.getInvocieType)
  router.post("/getLeaveType",dataController.getLeaveType)
  router.post("/getSelectSlot",dataController.getSelectSlot)
  router.post("/getDashBoardType",dataController.getDashBoardType)
  router.post("/getGST",dataController.getGST)
  router.post("/getPartyName",dataController.getPartyName)
  router.post("/getGSTReport",dataController.getGSTReport)
  router.post("/getType",dataController.getType)
  router.post("/getAccrual",dataController.getAccrual)
  router.post("/getExceedLeave",dataController.getExceedLeave)
  router.post("/getLeaveReason",dataController.getLeaveReason)
  router.post("/getPendingStatus",dataController.getPendingStatus)
  router.post("/getdefCustomer",dataController.getdefCustomer)
  router.post("/getSalesMode",dataController.getSalesMode)
  router.post("/getPurchaseAnalysis",dataController.getPurchaseAnalysis)
  router.post("/getTaskstatus",dataController.getTaskstatus)
  router.post("/PendingCustomer",dataController.PendingCustomer)
  router.post("/getPriority",dataController.getPriority)
  router.post("/getAnnouncementDuration",dataController.getAnnouncementDuration)
  router.get("/usercode",dataController.getUsercode)
  router.post("/Fame_atten_report",dataController.Fame_atten_report)
  router.get("/getDeptType_Atte_Report",dataController.getDeptType_Atte_Report)
  router.post("/Fame_atten_contract",dataController.Fame_atten_contract)
  router.get("/getcontractorname",dataController.getcontractorname)
  router.get("/fame_emp_details",dataController.fame_emp_details)
  router.get("/getDeptType_Daily_Atte_Report",dataController.getDeptType_Daily_Atte_Report)
  router.post("/Fame_atten_machine_log_report",dataController.Fame_atten_machine_log_report)
  router.post("/getColumn",dataController.getColumn)
  router.post("/getEmployeeBasicDetails",dataController.getEmployeeBasicDetails)
  router.post("/getEmployeesearchcriteria",dataController.getEmployeesearchcriteria)
  router.get("/GetCompanyCode",dataController.GetCompanyCode)
  router.get("/GetDeptCode",dataController.GetDeptCode)
  router.post("/GetemployeeFullDetails",dataController.GetemployeeFullDetails)
  router.post("/TemplateInsert",dataController.TemplateInsert)
  router.post("/FetchTemplate",dataController.FetchTemplate)
  router.post("/FetchGridTemplate",dataController.FetchGridTemplate)
  router.post("/TemplateList",dataController.TemplateList)
  router.post("/logout",dataController.logout)
  router.get("/getLicenseDetails",dataController.getLicenseDetails)
  router.post("/addSettings",dataController.addSettings)
  router.post("/getSettings",dataController.getSettings)
  router.post("/getIdleTime",dataController.getIdleTime)
  router.post("/updateRoleRights",dataController.updateRoleRights)
  router.post("/LeaveMasterInsert",dataController.LeaveMasterInsert)
  router.post("/LeaveMasterUpdate",dataController.LeaveMasterUpdate)
  router.post("/LeaveMasterSearch",dataController.LeaveMasterSearch)
  router.post("/LeaveMasterGridUpdate",dataController.LeaveMasterGridUpdate)
  router.post("/LeaveMasterGridDelete",dataController.LeaveMasterGridDelete)
  router.post("/getEmployeeDelete",dataController.getEmployeeDelete)
  router.get("/Companyno",dataController.getCompanyno)
  router.post("/companysearchcriteria",dataController.getsearchdata)
  router.post("/add", upload.fields([
    { name: 'company_logo', maxCount: 1 },
    { name: 'authorisedSignatur', maxCount: 1 }
  ]),dataController.addData)
  router.post("/saveEditedData", dataController.saveEditedData);
  router.post("/delete", dataController.deleteData);
  router.post("/CompanyUpdate",
    upload.fields([
    { name: 'company_logo', maxCount: 1 },
    { name: 'authorisedSignatur', maxCount: 1 }
  ]), dataController.CompanyUpdate);

module.exports = router;
     